export default{
	"alarm-list":"告警明细",
	"trend-list": "趋势图预警",
	"tablespace": "表空间预警",
	"section-space": "段空间预警",
	"sql-report": "SQL区段报表",
	"sql-bind": "SQL区段绑定变量",
	"trend-metric": "关键指标趋势",
	"session-history": "活动会话历史",
	"awr-snapshot": "AWR快照报表",
	"sql-quote": "SQL全文索引",
	"quote-report": "索引访问报表",
	"record-change": "记录变更报表",
	"order-report": "序列变更报表",
	"data-dict": "数据字典",
	"tablespace-report": "表空间报表",
	"sectionspace-report": "段空间报表",
	"user-manager": "用户管理",
	"role-manager": "角色管理",
	"host-manager": "主机管理",
	"host-group": "主机群组",
	"template-manager": "模板管理",
	"except-manager": "异常管理",
	"login-rank": "登录排行"
}